import { Hero } from '../models/hero';

export const HEROES: Hero[] = [
  {
    id: 111,
    alias: 'Batman',
    name: 'Bruce Thomas Wayne',
    image: '/assets/images/batman.jpg',
    desc: 'In the name of his murdered parents, Bruce Wayne wages eternal war on the criminals of Gotham City. He is vengeance. He is the night. He is Batman. One of the most iconic fictional characters in the world, Batman has dedicated his life to an endless crusade, a war on all criminals in the name of his murdered parents, who were taken from him when he was just a child. Since that tragic night, he has trained his body and mind to near physical perfection to be a self-made Super Hero. He is developed an arsenal of technology that would put most armies to shame. And he is assembled teams of his fellow DC Super Heroes, like the Justice League, the Outsiders and Batman, Incorporated. A playboy billionaire by day, Bruce Wayne is double life affords him the comfort of a life without financial worry, a loyal butler-turned-guardian and the perfect base of operations in the ancient network of caves beneath his family is sprawling estate. By night, however, he sheds all pretense, dons his iconic scalloped cape and pointed cowl and takes to the shadowy streets, skies and roof tops of Gotham City.',
    power: 'exceptional martial artist, combat strategy, inexhaustible wealth, brilliant deductive skill, advanced technology',
    video: 'dl3wFQlOKwY',
  },
  {
    id: 112,
    name: 'T Challa',
    image: '/assets/images/black_panther.jpg',
    desc: 'Black Panther is the title held by T Challa, a member of the royal family of the fictional African country of Wakanda. After the death of his father, T Challa claimed the throne and the role of Black Panther. He was exposed to a mystical herb that enhanced his strength and agility to near-superhuman levels.',
    alias: 'Black Panther',
    power : 'The power to draw upon the knowledge, strength, and every experience of every previous Black Panther. Superhuman strength, speed, reflexes, agility, stamina, endurance, durability, and senses. Genius-level intellect. Master martial artist, tactician, strategist, and inventor. Utilizing vibranium suit and equipment',
    video: '8ck8pVhsWLU',
  },
  {
    id: 113,
    alias: 'Black Widow',
    name: 'Natalia Alianovna',
    image: '/assets/images/black_widom.jpg',
    desc: 'Natalia Alianovna "Natasha Romanoff" Romanova, colloquial: Black Widow is a fictional superhero appearing in American comic books published by Marvel Comics. Created by editor and plotter Stan Lee, scripter Don Rico, and artist Don Heck, the character debuted in Tales of Suspense #52.',
    power : 'Expert tactician, hand-to-hand combatant and secret agent. Slowed aging, and enhanced immune system. Expert marksman and mastery of various other weapons. Equipment via gauntlets: grappling hook, knock out gas, taser, explosives, tear gas pellets, radio transmitter',
    video: 'FiBPw15KAl4',
  },
  {
    id: 114,
    alias: 'Captain America',
    name: 'Steve Rogers',
    image: '/assets/images/captain_america.jpg',
    desc: 'Captain America is the alter ego of Steve Rogers, a frail young man enhanced to the peak of human perfection by an experimental serum to aid the United States government is efforts in World War II. Near the end of the war, he was trapped in ice and survived in suspended animation until he was revived in modern times',
    power : 'Enhanced strength, speed, stamina, durability, agility, reflexes, senses, and mental processing via the super soldier serum. Master martial artist and hand-to-hand combatant. Accelerated healing. Immunity to diseases and toxins. Slowed aging. Master tactician, strategist, and field commander. Using Vibranium-steel alloy shield',
    video: '-S56HRfAfqI',
  },
  {
    id: 115,
    name: 'Carol Danvers',
    image: '/assets/images/captain_marvel.jpg',
    desc: 'Former Air Force pilot and intelligence agent Carol Danvers pursued her dream of space exploration as a NASA employee, but her life forever changed when she was accidentally transformed into a human-Kree hybrid with extraordinary powers. Now, Carol is the latest warrior to embrace the mantle of Captain Marvel, and she has taken her place as one of the world is mightiest heroes.',
    alias: 'Captain Marvel',
    power : 'Superhuman strength, speed, endurance, and stamina. Energy absorption and projection. Flight',
    video: 'YAGHsKoEv44',
  },
  {
    id: 116,
    alias: 'Cyclops',
    name: 'Scott Summers',
    image: '/assets/images/cyclops.jpg',
    desc: 'Created by writer Stan Lee and artist/co-writer Jack Kirby, the character first appeared in the comic book The X-Men. Cyclops is a member of a subspecies of humans known as mutants, who are born with superhuman abilities. Cyclops can emit powerful beams of energy from his eyes.',
    power : 'Optic blasts. Master tactician and strategist. Skilled martial artist and hand-to-hand combatant',
    video: 'R8nWG456o-Q',
  },
  {
    id: 117,
    alias: 'DareDevil',
    name: 'Matthew Murdock',
    image: '/assets/images/daredevil.jpg',
    desc: 'Premise. The first season sees lawyer-by-day Matt Murdock use his heightened senses from being blinded as a young boy to fight crime at night on the streets of New York City is Hell is Kitchen neighborhood as Daredevil, while uncovering a conspiracy of the criminal underworld being led by Wilson Fisk.',
    power : 'Superhuman senses. Echolocative radar sense. Skilled acrobat, martial artist, and stick fighter. Utilization of specially-designed billy club',
    video: '2N_0hvICKzg',
  },
  {
    id: 118,
    alias: 'Doctor Strange',
    name: 'Stephen Strange',
    image: '/assets/images/doctor_strange.jpg',
    desc: 'Doctor Strange is described as "the mightiest magician in the cosmos" and "more powerful by far than any of your fellow humanoids" by Eternity, the sentience of the Marvel Universe.',
    power : 'Mastery of magic. Utilizes mystical artifacts. such as the Cloak of Levitation and the Eye of Agamotto. Genius-level intellect. Skilled martial artist. Gifted physician and surgeon',
    video: 'FQew3FzqBw4',
  },
  {
    id: 119,
    alias: 'Iron Man',
    name: 'Tony Stark',
    image: '/assets/images/ironman.jpg',
    desc: 'Iron Man is a fictional superhero appearing in American comic books published by Marvel Comics. ... Later, Stark develops his suit, adding weapons and other technological devices he designed through his company, Stark Industries. He uses the suit and successive versions to protect the world as Iron Man.',
    power : 'Genius level intellect. Proficient scientist and engineer. Powered armor suit : Superhuman strength, speed, durability, agility, reflexes, and senses. Supersonic flight. Energy repulsor and missile projection. Regenerative life support',
    video: '5-Cx7UslEuE',
  },
  {
    id: 120,
    alias: 'Phoenix',
    name: 'Jean Grey',
    image: '/assets/images/phoenix.jpg',
    desc: 'For months the Phoenix believed itself to be the real Jean and saved the universe by healing the MKraan Crystal. Mental manipulation by Mastermind caused Phoenix to go insane and become Dark Phoenix. ... Eventually, Jean was rescued from her stasis and, with the other original X-Men, formed a new team, X-Factor.',
    power : 'Telepathy. Telekinesis. While acting as avatar for the Phoenix Force. Jean is own powers are magnified, including matter manipulation on atomic level, teleportation, and immortality',
    video: 'p1X5A9Nmsy4',
  },
  {
    id: 121,
    alias: 'Superman',
    name: 'Clark Kent',
    image: '/assets/images/superman.jpg',
    desc : 'Faster than a speeding bullet, more powerful than a locomotive… The Man of Steel fights a never-ending battle for truth, justice, and the American way. From his blue uniform to his flowing red cape to the "S" shield on his chest, Superman is one of the most immediately recognizable and beloved DC Super Heroes of all time. The Man of Steel is the ultimate symbol of truth, justice, and hope. He is the world is first Super Hero and a guiding light to all. The tip of the spear in a revolution that would change the landscape of pop culture, Superman has spent the last eighty years redefining what it means to stand for truth, justice and the American way. The last survivor of the doomed planet Krypton, raised in the quiet heartland of Smallville, Kansas, Superman is as much a legend as he is a man: the gold standard of heroism, compassion and responsibility. Though his powers make him god-like next to his human compatriots, Superman is story is not one of greed or conquest. Instead, he strives to represent the inherent goodness of the human spirit, and the capacity of every living thing to do right by their neighbors.',
    power: 'Super strength. Flight, invulnerability, super speed, heat vision, freeze breath, x-ray vision, superhuman hearing, healing factor',
    video: 'zXrpjlXE6B0',
  },
  {
    id: 122,
    alias: 'Wonder Woman',
    name: 'Diana Prince',
    image: '/assets/images/wonder_woman.jpg',
    desc : 'Beautiful as Aphrodite, wise as Athena, swifter than Hermes, and stronger than Hercules, Princess Diana of Themyscira fights for peace in Man is World. One of the most beloved and iconic DC Super Heroes of all time, Wonder Woman has stood for nearly eighty years as a symbol of truth, justice and equality to people everywhere. Raised on the hidden island of Themyscira, also known as Paradise Island, Diana is an Amazon, like the figures of Greek legend, and her people is gift to humanity. As Themyscira is emissary to Man is World, Diana has made it her duty to lead by example, even if the differences between her birthplace and new home sometimes present hurdles for her to jump. She has come to represent the possibility and potential of life without war, hate or violence, and she is a beacon of hope to all who find themselves in need. She stands as an equal among the most powerful Super Heroes, with a sense of purpose to protect the world from injustice in all forms. Diana is job, however, is anything but easy. Constantly torn between her mission to promote peace and her need to fight back against the pervasive violence of her new home, Diana struggles to walk a line between her warrior strength and endless compassion each and every day.',
    power : 'Super strength, invulnerability, flight, combat skill, combat strategy, superhuman agility, healing factor, magic weaponry',
    video: 'UsinZA1NZ8U',
  },
  {
    id: 123,
    alias: 'Storm',
    name: 'Ororo Munroe',
    image: '/assets/images/storm.jpg',
    desc: 'Descended from a long line of African witch-priestesses, Storm is a member of a fictional subspecies of humans born with superhuman abilities known as mutants. She is able to control the weather and atmosphere and is considered to be one of the most powerful mutants on the planet.',
    power : 'Expert tactician and thief. Psionic ability to manipulate weather patterns over vast area. Control atmospheric pressure. Temperature modification. Ecological empathy. Flight, electricity manipulation. Limited immunity to extreme cold and heat',
    video: '06bgrEsf35Q',
  },
  {
    id: 124,
    alias: 'Thor',
    name: 'Thor Odinson',
    image: '/assets/images/thor.jpg',
    desc: 'Thor is an extremely powerful warrior, and one of the strongest beings on Marvel Earth, his strength having often been compared to that of the Hulk. He also wields a magical hammer that is not only very powerful, but also has numerous mystical powers. Thor possess the superhuman physical attributes of an Asgardian.',
    power : 'Superhuman strength, speed, durability and longevity. Abilities via Mjolnir: Dimensional transportation, electric manipulation, flight, weather manipulation',
    video: 'abM1Z3fYT3s',
  },
  {
    id: 125,
    alias: 'Wolverine',
    name: 'Logan / James Howlett',
    image: '/assets/images/wolverine.jpg',
    desc: 'He is a mutant who possesses animal-keen senses, enhanced physical capabilities, a powerful regenerative ability known as a healing factor, and three retractable claws in each hand. Wolverine has been depicted variously as a member of the X-Men, Alpha Flight, and the Avengers.',
    power : 'Enhanced strength, speed, stamina, durability, endurance, agility, reflexes, dexterity, resilience, flexibility, coordination, balance, and reaction time. Superhuman senses, and animal-like attributes, Regeneration and slowed aging, Indestructible bones via adamantium-infused skeleton, Retractable adamantium claws, Retractable bone claws, Master hand-to-hand combatant and martial artist',
    video: '_KYMHfVfmu0',
  },
  {
    id: 126,
    alias: 'Punisher',
    name: 'Frank Castle',
    image: '/assets/images/punisher.jpg',
    desc: 'A war veteran and a USMC Scout/Sniper in Force Recon, Castle is skilled in hand-to-hand combat, guerrilla warfare, and marksmanship. He is well known by his skull motif on his chest. The Punisher is brutal nature and willingness to kill made him an anomaly in mainstream American comic books when he debuted in 1974.',
    power : 'Peak physical conditioning and abnormally high pain tolerance. Skilled in guerrilla warfare, military tactics, close quarters combat, infiltration, marksmanship, demolitions, and unarmed combat. Expert investigator and interrogator. Expert knowledge in methods of both criminals and law enforcement. Various US Military special operations training',
    video: 'o7GwgTCTigc',
  },
  {
    id: 127,
    alias: 'Spiderman',
    name: 'Peter Parker',
    image: '/assets/images/spiderman.jpg',
    desc: 'Superhuman strength, agility, endurance, ability to stick to and climb walls and other surfaces, uses self-designed web-shooters allowing him to fire and swing from sticky webs, special "Spider-Sense" warns of incoming danger, genius intellect specializing in chemistry and invention.',
    power : 'Genius intellect. Proficient scientist and inventor. Superhuman strength, speed, durability, agility, stamina, reflexes/reactions, coordination, balance and endurance. Precognitive spider-sense ability, cling to most solid surfaces and webbing ability. Utilizing wrist web-shooters to shoot spider web-like material',
    video: 'zceKndOf6qY',
  },
  {
    id: 128,
    alias: 'Shazam',
    name: 'Billy Batson',
    image: '/assets/images/black_adam.jpg',
    desc : 'When Billy Batson speaks the name of an ages-old wizard, he is transformed into the World is Mightiest Mortal—Shazam! Billy Batson’s parents died when he was still a baby. The orphaned child believed he had no one to rely on and had to fend for himself. But one day, he was guided to the Rock of Eternity, where the ancient wizard Shazam waited. The world needed heroes and the boy became the wizard’s new champion, able to transform himself into an adult superhero by calling down a magical bolt of lightning. Now, whenever evil must be stopped or people are in need of help, Earth can rely on the power of Shazam!',
    power : 'super strength, flight, invulnerability, super speed, superhuman hearing, healing factor, intelligence, magic',
    video: 'Vsy-5WSUvFM',
  },
];
